<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="252" started-at="2016-11-13T17:21:53Z" finished-at="2016-11-13T17:21:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="252" started-at="2016-11-13T17:21:53Z" finished-at="2016-11-13T17:21:54Z">
      <class name="TestNG_Listerners.Implementing_Listeners">
        <test-method status="PASS" signature="method_2()[pri:0, instance:TestNG_Listerners.Implementing_Listeners@2fab0086]" name="method_2" duration-ms="83" started-at="2016-11-13T22:51:53Z" finished-at="2016-11-13T22:51:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_2 -->
        <test-method status="FAIL" signature="method_4()[pri:0, instance:TestNG_Listerners.Implementing_Listeners@2fab0086]" name="method_4" duration-ms="8" started-at="2016-11-13T22:51:53Z" finished-at="2016-11-13T22:51:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Banga] but found [Bangalore]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Banga] but found [Bangalore]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at TestNG_Listerners.Implementing_Listeners.method_4(Implementing_Listeners.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_4 -->
      </class> <!-- TestNG_Listerners.Implementing_Listeners -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
